name: Convert IPYNB to HTML and Deploy

on:
  push:
    branches:
      - main  # Cambia esto por la rama en la que quieres que se ejecute la acción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert notebook to HTML
      run: |
        jupyter nbconvert --to html Untitled.ipynb

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Untitled_files  # Directorio que contiene el archivo HTML convertido
        publish_branch: gh-pages
